### ISSUE TITLE
Tests failing on clean install

### ISSUE THREAD

**Issue by rngadam** [Prepsmith/circleci_webhook_listener#5]
```
rngadam@rngadam-mac ~/E/s/circleci_webhook_listener> npm run test

> pad_sales_tool_webhook@0.1.0 test /Users/rngadam/EIC/src/circleci_webhook_listener
> mocha

loading settings from settings.json


{ Error: ENOENT: no such file or directory, open '/Users/rngadam/EIC/src/circleci_webhook_listener/settings.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/rngadam/EIC/src/circleci_webhook_listener/settings.json' }
  WebHook unit tests
    AppendToken
      ✓ works with correct input
      ✓ doesn't work when there is no https
      ✓ doesn't work when there is no url
    obtainArtifactsUrl
      1) works with correct input
      ✓ doesn't work when there is no build number
    obtainAPKpath
      2) works with correct input
      ✓ doesn't work when there is no url
      ✓ doesn't work when there is apk file in the path
    Download
      ✓ downloads bing (793ms)
      ✓ doesn't work when there is no uri
      ✓ doesn't work when there is no file path


  9 passing (812ms)
  2 failing

  1) WebHook unit tests obtainArtifactsUrl works with correct input:
     Error: url 'NaN/artifacts' doesn't start with correct https prefix
      at appendToken (app.js:84:46)
      at Object.obtainArtifactsUrl (app.js:93:5)
      at Context.<anonymous> (test/unit_tests.js:41:17)

  2) WebHook unit tests obtainAPKpath works with correct input:
     TypeError: path must be a string or Buffer
      at Object.fs.mkdir (fs.js:839:11)
      at Object.obtainAPKpath (app.js:109:8)
      at Context.<anonymous> (test/unit_tests.js:57:19)
```

**Comment by thimovss** [comment]
Issue should be resolved, if not please reopen the issue.
